### ISSUE TITLE
Typo: Hackaton

### ISSUE THREAD

**Issue by expede** [filecoin-station/filstation.app#3]
This is probably meant to be "Station Runtime Hackat[h]on" 😉 

<img width="416" alt="Screenshot 2023-02-20 at 19 59 40" src="https://user-images.githubusercontent.com/1052016/220244241-f4e3a81e-1e78-4a5c-94dd-09330e8e116c.png">

**Comment by juliangruber** [comment]
thank you! Fixed :)

Ref https://github.com/filecoin-station/roadmap/issues/11
